WebAppArticles/urls.py
from django.contrib import admin
from django.urls import include, path
from articles.views import frontpageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", frontpageView, name = "frontpage" ),
    path('users/', include('users.urls')),
    path('articles/', include('articles.urls')),
]

articles/urls.py
from django.urls import path
from .views import *

app_name = 'articles'
urlpatterns = [
    path('<int:pk>', articleView, name = 'article'),
    path('create', createView, name = 'create'),
    path('<int:pk>/delete', deleteView, name = 'delete'),
    path('<int:pk>/like', likeView, name = 'like'),
    path('<int:pk>/edit', editView, name = 'edit'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path("<int:id>", profileView, name = "profile"),
    path("login", loginView, name = "login"),
    path("logout", logoutView, name = "logout"),
    path("signup", signupView, name = "signup"),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length = 64, default = None)
    author = models.ForeignKey(User, on_delete = models.CASCADE, default = None, related_name = "author")
    published = models.BooleanField(default = False)
    date = models.DateTimeField(default = None)
    content = models.JSONField(default = dict)
    users_liked = models.ManyToManyField(User, related_name = "users_liked")

    def __str__(self) -> str:
        return f"Article: {self.title}\nID: {self.pk}\nDate: {self.date}\nLikes: {self.countLikes()}\n\n"
    
    def countLikes(self) -> int:
        return self.users_liked.count()

users/models.py
from django.db import models
from django.contrib.auth.models import User

articles/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET
from django.shortcuts import render, redirect
from WebAppArticles.misc import htmlBuilder, getLiked
from django.http import HttpResponse
from django.utils import timezone
from .models import Article
from WebAppArticles.misc import user_isauthor
import json


def articleView(request, pk):
    article = Article.objects.get(id = pk)
    context = {
        "article": article,
        "content": htmlBuilder(False, article.content),
        "liked": getLiked(request.user.id),
    }
    return render(request, 'article.html', context)


@require_GET
@login_required(login_url = "users:signup")
def createView(request):
    article = Article.objects.create(
        title = "Sample Title",
        author = request.user,
        published = False,
        date = timezone.now(),
        content = [[{"type": "h1", "content" : "Sample"}]],
    )
    article.save()
    return redirect('articles:edit', pk = article.pk)

@require_POST
@user_isauthor(redirect_url = "frontpage")
@login_required(login_url = "users:signup")
def deleteView(request, pk):
    article = Article.objects.get(id = pk)
    author_id = article.author.id
    article.delete()

    origin = request.META["HTTP_REFERER"]
    return redirect(origin, id = author_id)

@require_POST
@login_required(login_url = "users:signup")
def likeView(request, pk):
    article = Article.objects.get(id = pk)
    origin = request.META["HTTP_REFERER"]
    if article.users_liked.contains(request.user):
        article.users_liked.remove(request.user)
    else:
        article.users_liked.add(request.user)

    return redirect(origin, pk = pk)


@user_isauthor(redirect_url = "frontpage")
@login_required(login_url = "users:signup")
def editView(request, pk):
    a = Article.objects.get(id = pk)
    
    if request.method == "POST":
        packet = json.loads(request.body.decode("utf-8"))

        if a:
            a.title = packet["title"]
            a.content = packet["blocks"]
            a.published = packet["published"]
            if a.published:
                a.date = timezone.now()
            a.save()
        
        return HttpResponse("Error 404")
    
    
    else:
        context = {
            "article": a,
            "content": htmlBuilder(
                editor = True,
                blocks = a.content,
            ),
        }
        return render(request, 'editor.html', context = context)


def frontpageView(request):
    article = Article.objects.all()
    context = {
        "trending": article,
        "mostliked": article,
        "liked": getLiked(request.user.id),
    }
    return render(request, 'frontpage.html', context)

users/views.py
from django.shortcuts import redirect, render, HttpResponse
from articles.models import Article
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from WebAppArticles.misc import logout_required, getLiked
from django.urls import reverse

def profileView(request, id):
    profile = User.objects.get(id = id)
    if profile:
        
        user_articles = Article.objects.filter(author = profile)
        total_likes = 0

        for article in user_articles:
            total_likes += article.users_liked.count()
        
        context = {
            "profile": profile,
            "profile_likes": total_likes,
            "liked": getLiked(request.user.id),
            "articles": Article.objects.all().filter(author = profile), 
        }
        
        return render(request, "profile.html", context)
    return HttpResponse("There isn't such user")

@logout_required(redirect_url = "frontpage")
def loginView(request):
    form = AuthenticationForm(None, data = request.POST)
    context = {
        "form": form,
    }

    if hasattr(request, "POST") and request.POST != {}:
        if form.is_valid():        
            login(request, form.get_user())
            return redirect(reverse("frontpage"))

    return render(request, 'login.html', context)

@login_required(login_url = "users:signup")
def logoutView(request):
    logout(request)
    return redirect(reverse("frontpage"))

@logout_required(redirect_url = "frontpage")
def signupView(request):
    form = UserCreationForm(request.POST or None)
    context = {
        "form": form,
    }
    if hasattr(request, "POST") and request.POST != {}:
        if form.is_valid():
            user = form.save()
            user.is_active = True
            user.save()
            login(request, user)

            return redirect(reverse("frontpage"))

    return render(request, 'signup.html', context)

articles/templates/article.html
{% load static %}
<link rel = "stylesheet" href = "{% static 'css/universal.css' %}">
<link rel = "stylesheet" href = "{% static 'css/article.css' %}">

<!DOCTYPE html>
<html>
    <body>
        {% include 'header.html' %}
        <div id = "header">
            <h1>{{article.title}}</h1>
            <div>
                <p>Author: <a href="{% url 'users:profile' article.author.id %}">{{article.author.username}}</a></p> 
                <p>Posted on {{ article.published|date:'d F Y' }}</p>
            </div>
            {% if request.user == article.author %}
                <div>
                    {% include 'edit.html' %}
                    {% include 'delete.html' %}
                </div>
            {% endif %}
            <div>
                <p>Likes: {{article.countLikes}}</p>
                {% include 'like.html'%}
            </div>
        </div>
        
        <div id = "article">
            {{content|safe}}
        </div>
        
        <!-- Footer block -->
        {% include 'footer.html' %}
    </body>
</html>

articles/templates/editor.html
{% load static %}
<link rel = "stylesheet" href = "{% static 'css/universal.css' %}">
<link rel = "stylesheet" href = "{% static 'css/editor.css' %}">


<!DOCTYPE html>
<html>
    <body>
        <header>
            {% include 'back.html' %}
            <input id = "title" value = "{{article.title}}"></input>
            <div id = "savebar">
                <div>
                    {% if article.published %}
                        <input type = "checkbox" id = "published" checked>
                    {% else %}
                        <input type = "checkbox" id = "published">
                    {% endif %}
                    <label for = "published">Published</label>
                </div>
                <button onclick = "sendPacket('{% url 'articles:edit' article.id %}')">Save</button>
            </div>
        </header>
        <div id = "content">
            {{content|safe}}
        </div>
        <div id = "navbar">
            <button onclick = "titleSpawn();">Add title</button>
            <button onclick = "paragrapghSpawn();">Add paragraph</button>
        </div>        
    </body>
    <script src = "{% static 'js/editor.js' %}"></script>
</html>

articles/templates/frontpage.html
{% load static %}
<link rel = "stylesheet" href = "{% static 'css/universal.css' %}">
<link rel = "stylesheet" href = "{% static 'css/frontpage.css' %}">

<!DOCTYPE html>
<html>
    <body>
        <!-- Header block -->
        {% include 'header.html'%}
        
        <!-- Carousels -->
        <div id = "carousels">
            <h1>Trending</h1>
            <div class = "carousel" id = "trending">
                {% include 'posts.html' with articles=trending %}
            </div>
            
            <h1>Most liked this week</h1>
            <div class = "carousel" id = "liked">
                {% include 'posts.html' with articles=mostliked %}
            </div>
        </div>

        <!-- Footer block -->
        {% include 'footer.html' %}
    </body>
</html>

misc/templates/back.html
<button onclick = "history.back()">Back</button>

misc/templates/delete.html
<form action = "{% url 'articles:delete' article.id %}" method = "post">
    {% csrf_token %}
    <button>Delete</button>
</form>

misc/templates/edit.html
<a href = "{% url 'articles:edit' article.id %}"><button>Edit</button></a>

misc/templates/footer.html
<footer>
    <p>Articles</p>
    <img src="" alt="Github">
    <img src="" alt="VK">
    <img src="" alt="Telegram">
</footer>

misc/templates/header.html
<header>
    {% if request.path != "/" %}
        {% include 'back.html' %}
    {% endif %}

    <h1><a href = "{% url 'frontpage' %}">Articles</a></h1>

    <div id = "user">
        {% if not user.is_authenticated %}
            <a href = "{% url 'users:signup' %}"> Sign up</a>
        {% else %}
            <a href = "{% url 'users:logout' %}">Log out</a>
        {% endif %}
        
        {% if user.is_authenticated %}        
            <a href = "{% url 'users:profile' user.id %}">{{user.get_username}}</a>
        {% else %}
            <a href = "{% url 'users:login' %}">Log in</a>
        {% endif %}
    </div>

</header>

misc/templates/like.html
<form action = "{% url 'articles:like' article.id %}" method = "post">
    {% csrf_token %}
    <button>
        {% if article.id in liked %}
            Unlike
        {% else %}
            Like
        {% endif %}
    </button>
</form>

misc/templates/posts.html
{% for article in articles %}
    <div class = "article">
        <h1><a href = "{% url 'articles:article' article.id %}">{{article.title}}</a></h1>
        <a href="{% url 'users:profile' article.author.id %}">
            <p>Author: {{article.author.username}}</p> 
        </a>
        
        <div>
            {% if user == article.author %}
                {% include 'edit.html'%}
                {% include 'delete.html'%}
            {% endif %}
        </div>
        <div>
            <p>Likes: {{article.countLikes}}</p>
            {% include 'like.html' %}
        </div>
    </div>
{% endfor %}

users/templates/login.html
{% load static %}
<link rel = "stylesheet" href = "{% static 'css/universal.css' %}">

<!DOCTYPE html>
<html>
    <body>
        <a id = "back" href = "{% url 'frontpage' %}">
            Back to frontpage
        </a>
        <h1>Log in</h1>
        <form id = "form" method = "post" action = "{% url 'users:login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Login</button>
        </form>
        <a href = "{% url 'users:signup' %}">Don't have an account?</a>
    </body>
</html>

users/templates/profile.html
{% load static %}
<link rel = "stylesheet" href = "{% static 'css/universal.css' %}">
<link rel = "stylesheet" href = "{% static 'css/profile.css' %}">

<!DOCTYPE html>
<html>
    <body>
        <!-- Header block -->
        {% include 'header.html' %}

        <div id = "profile">
            <h1>{{profile.get_username}}</h1>
            <p>Total likes: {{likes}}</p>
            {% if profile == user %}
                <a href = "{% url 'articles:create' %}">
                    <button>Create article</button>
                </a>
            {% endif %}
        </div>


        <h1>Articles</h1>
        <div id = "articles">
            {% include 'posts.html' %}
        </div>


        <!-- Footer block -->
        {% include 'footer.html' %}
    </body>
</html>

users/templates/signup.html
{% load static %}
<link rel = "stylesheet" href = "{% static 'css/universal.css' %}">

<!DOCTYPE html>
<html>
    <body>
        <a id = "back" href = "{% url 'frontpage' %}">
            Back to frontpage
        </a>
        <h1>Sign up</h1>
        <form id = "form" method = "post" action = "{% url 'users:signup' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Sign up</button>
        </form>
        <a href = "{% url 'users:login' %}">Already have an account?</a>
    </body>
</html>